/* Generated By:JavaCC: Do not edit this line. testConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface testConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 1;
  /** RegularExpression Id. */
  int INCLUDE = 2;
  /** RegularExpression Id. */
  int MESSAGE = 3;
  /** RegularExpression Id. */
  int RETURN = 4;
  /** RegularExpression Id. */
  int VOID = 5;
  /** RegularExpression Id. */
  int LEER = 6;
  /** RegularExpression Id. */
  int SISTEMA = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int SWITCH = 10;
  /** RegularExpression Id. */
  int CASE = 11;
  /** RegularExpression Id. */
  int PREDETERMINADO = 12;
  /** RegularExpression Id. */
  int BREAK = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int FOR = 16;
  /** RegularExpression Id. */
  int PARENTESISIZQ = 17;
  /** RegularExpression Id. */
  int PARENTESISDER = 18;
  /** RegularExpression Id. */
  int LLAVEIZQ = 19;
  /** RegularExpression Id. */
  int LLAVEDER = 20;
  /** RegularExpression Id. */
  int NUMERAL = 21;
  /** RegularExpression Id. */
  int PUNTOYCOMA = 22;
  /** RegularExpression Id. */
  int DOSPUNTOS = 23;
  /** RegularExpression Id. */
  int COMILLADOB = 24;
  /** RegularExpression Id. */
  int COMA = 25;
  /** RegularExpression Id. */
  int PUNTO = 26;
  /** RegularExpression Id. */
  int PORCENTAJE = 27;
  /** RegularExpression Id. */
  int AMPERSAND = 28;
  /** RegularExpression Id. */
  int ASIGNACION = 29;
  /** RegularExpression Id. */
  int INCREMENTO = 30;
  /** RegularExpression Id. */
  int DECREMENTO = 31;
  /** RegularExpression Id. */
  int MENOR = 32;
  /** RegularExpression Id. */
  int MAYOR = 33;
  /** RegularExpression Id. */
  int MENORIGUAL = 34;
  /** RegularExpression Id. */
  int MAYORIGUAL = 35;
  /** RegularExpression Id. */
  int IGUAL = 36;
  /** RegularExpression Id. */
  int DISTINTO = 37;
  /** RegularExpression Id. */
  int AND = 38;
  /** RegularExpression Id. */
  int OR = 39;
  /** RegularExpression Id. */
  int NOT = 40;
  /** RegularExpression Id. */
  int ENTERO = 41;
  /** RegularExpression Id. */
  int DOBLE = 42;
  /** RegularExpression Id. */
  int CADENA = 43;
  /** RegularExpression Id. */
  int INT = 44;
  /** RegularExpression Id. */
  int FLOAT = 45;
  /** RegularExpression Id. */
  int STRING = 46;
  /** RegularExpression Id. */
  int NUMERO = 47;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"main\"",
    "\"include\"",
    "\"mensaje\"",
    "\"regresar\"",
    "\"void\"",
    "\"leer\"",
    "\"sistema\"",
    "\"si\"",
    "\"si no\"",
    "\"menusi\"",
    "\"caso\"",
    "\"predeterminado\"",
    "\"Salir\"",
    "\"mientras\"",
    "\"hacer\"",
    "\"para\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"#\"",
    "\";\"",
    "\":\"",
    "\"\\\"\"",
    "\",\"",
    "\".\"",
    "\"%\"",
    "\"&\"",
    "\"=\"",
    "\"++\"",
    "\"--\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"y\"",
    "\"o\"",
    "\"no\"",
    "\"entero\"",
    "\"doble\"",
    "\"cadena\"",
    "\"int\"",
    "\"float\"",
    "\"string\"",
    "<NUMERO>",
    "<IDENTIFICADOR>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
  };

}
